### ISSUE TITLE
Problem receiving message, an example would help

### ISSUE THREAD

**Issue by JediMindtrick** [kifi/franz#27]
An end-to-end example of 1) create queue, 2) send message, 3) receive message and 4) delete queue would be a really helpful little piece of documentation.

As it is, I can accomplish 1 & 2, but not 3.  I am a scala noob, for sure, so chances are high that I'm just missing something obvious.  The symptom that I see is that my onComplete never seems to get called.  When executed at the command-line the program will run for about a minute and then exit.

Here is some really basic code of mine that does not do 3:

```
package com.learnAWSScala 

import com.amazonaws.regions.Regions
import scala.concurrent._
import ExecutionContext.Implicits.global
import scala.concurrent.duration
import scala.util.{Success, Failure}

import com.kifi.franz.SimpleSQSClient

object Hello {

  def main(args : Array[String]) = {
    println("Hello World") 

    val sqs = SimpleSQSClient("MY ID HERE", "MY SECRET HERE", Regions.US_EAST_1)

    val q = sqs.simple(com.kifi.franz.QueueName("testScalaQueue"), true)

    q.send("Hello AWS!")

    val msg = q.next(scala.concurrent.ExecutionContext.global)

    msg onComplete {
      case Success(message) => println("got a message")
      case Failure(t) => println("An error has occured")
    }

    println("More stuff")
  }
}
```

**Comment by ilanbiala** [comment]
@JediMindtrick what library are you using for SQS support in Scala?

**Comment by JediMindtrick** [comment]
@ilanbiala Sorry, that was a learning project and it looks like I scrapped it.
