### ISSUE TITLE
Receiving messages does not work when buffered=true.

### ISSUE THREAD

**Issue by goldmar** [kifi/franz#36]
Hi,

I've got the same issue as #22 - receiving messages does not work when `buffered=true`. `buffered=false` remedies the problem, however it's a bad solution because it disables buffering of the deletion requests.

Any ideas what causes the problem? To improve the usability of the library I suggest setting the default to `false` and adjust the Readme while this option does not work.

Best,
Mark

**Comment by alesilva** [comment]
I've got the same issue.

Best,
Alexandre

**Comment by stkem** [comment]
As best I can tell, this is a problem with the underlying Java library from Amazon. I was hoping it would fix itself as they release a new version, but that hasn't happened. It's time to at least change the default. Update coming shortly.
