### ISSUE TITLE
Multicasting

### ISSUE THREAD

**Issue by neil-rubens** [kifi/franz#40]
In `Readme` as one of the limitations it is mentioned that `Multicasting is really cumbersome
`.

Multicasting could be easily achieved with [SNS fanout](https://aws.amazon.com/blogs/aws/queues-and-notifications-now-best-friends/).

p.s. thanks for a nice library

**Comment by stkem** [comment]
Care to send a PR? :-)

**Comment by neil-rubens** [comment]
Thanks, I'll send a PR in a couple of days.
