### ISSUE TITLE
Maven update

### ISSUE THREAD

**Issue by jeffsteinmetz** [kifi/franz#43]
Some documentation as well as some API updates have been merged to master.
The README references the latest version as 0.3.9.

Can the Maven JAR be updated with the most recent merges to master, with a version bump to 0.3.10 ?

**Comment by jeffsteinmetz** [comment]
see PR
https://github.com/kifi/franz/pull/44

**Comment by stkem** [comment]
New version is publish. Might take a couple of hours before it shows up in central.
