### ISSUE TITLE
Duplicates while using enumerator/iteratee

### ISSUE THREAD

**Issue by kumaramit01** [kifi/franz#46]
This could potentially problem in my code or an issue in the implementation of enumerator. I see duplicates while using enumerator (I understand that SQS can occasionally return duplicate messages, but this is consistent). Maybe I am using enumerator/Iteratee incorrectly. Attached is the code.

Do you see anything fishy before I look more closely at the implementation.

Thanks
Amit

```scala
object SimSQSConsumer {
  def main(args:Array[String]):Unit={
    val awsKey = System.getProperty("aws.key")
    val awsSecret = System.getProperty("aws.secret")
    require(awsKey != null)
    require(awsSecret != null)
    import scala.concurrent._
    import ExecutionContext.Implicits.global
    val credentials = new AWSCredentials {
      def getAWSAccessKeyId() = awsKey
      def getAWSSecretKey() = awsSecret
    }
    val sqs = SimpleSQSClient(credentials, Regions.US_WEST_1, buffered = false)
    val queueName = QueueName("queue1")
    val queue = sqs.simple(queueName)
    def ensureIntervalIteratee = Iteratee.foreach{ message:SQSMessage[String] =>
      message.consume()
      println(message.body)
    }
   queue.enumerator.run(ensureIntervalIteratee)
  }

}
```
``` Shell
hello world 1
hello world 4
hello world 3
hello world 5
hello world 5
hello world 2
hello world 2
```
```scala
object SimSQSPublisher {

  def main(args: Array[String]): Unit = {

    val awsKey = System.getProperty("aws.key")
    val awsSecret = System.getProperty("aws.secret")

    require(awsKey != null)
    require(awsSecret != null)
    import scala.concurrent._
    import ExecutionContext.Implicits.global
    val credentials = new AWSCredentials {
      def getAWSAccessKeyId() = awsKey
      def getAWSSecretKey() = awsSecret
    }
    val sqs = SimpleSQSClient(credentials, Regions.US_WEST_1, buffered = false)
    val queueName = QueueName("queue1")
    val queue = sqs.simple(queueName)
    for(i <- 1 to 5) {
      val ft = queue.send("hello world "+ i)
      ft.onComplete {
        processSending
      }
    }
  }


  def processSending(message: Try[MessageId]): Unit = {
    message match {
      case Failure(ex) => {
        println("Failed sending:  " + ex)
      }
      case Success(messageId) => {
        println("Succeeded sending: " + messageId)
      }
    }
  }

}
```
```Shell
Succeeded sending: MessageId(a1aee4b5-b686-48e9-9276-cc6b0e7d3504)
Succeeded sending: MessageId(fe3ac294-92b0-4f30-aedb-5ed15047c440)
Succeeded sending: MessageId(7960f941-830e-4652-878e-93f8dc98f2f3)
Succeeded sending: MessageId(1574e78d-d8b2-4b5d-ab77-ccb2ba0a5d1d)
Succeeded sending: MessageId(20267698-2721-4ddb-933a-ce338306bcdf)
```

**Comment by stkem** [comment]
I see nothing obviously wrong with your code. Will poke around  a bit as well to see what is going on.

**Comment by codenamestif** [comment]
Got the same issue. I think it's because of async calls.
Now it's implemented using `Enumerator.repeatM` but should be `Enumerator.repeat`.
Also i guess there is the same issue if you use for example `next` method for several subscribers. They both could receive the same message at one time.

**Comment by stkem** [comment]
Not sure if you are still using this, but here goes anyway:
Fundamentally, SQS does only guarantee at-least-once delivery of messages, so it is always possible to get a message multiple times. In this particular case, I think the issue is with the asynchronous nature of the iteratee/enumerator. 
Since you are using `enumerator` (and not `enumeratorWithLock`) the message is fully available in the queue until consumed. If the thread that fetches stuff makes it to SQS before you call to `consume` does you'll get the same message again. I think the problem might be fixe by simple using `enumeratorWithLock` with a short timeout. A few seconds should be plenty.
