### ISSUE TITLE
README still suggests using 0.3.10 with buffered client

### ISSUE THREAD

**Issue by clementgarnier** [kifi/franz#51]
I understand previous issues and pull requests have pointed out that the underlying buffered client is unsafe, as well as explicitly set the `buffered` default value to `false` in all `SimpleSQSClient` constructors as of `0.3.11`.

However, the current `README` still:
+ Defines `0.3.10` as the current version
+ Suggests using a constructor that explicitly sets `buffered` to `true` as of `0.3.10`

I would suggest to:
+ Add additional warnings in the `README` about that constructor in `0.3.10`
+ Define `0.3.11` as the current version in the `README`

Not sure how versioning is handled so I'd rather discuss instead of blindly submitting a PR.

Thanks!

**Comment by stkem** [comment]
Thanks for pointing this out. I just updated the readme and release new version 0.3.13 with some other small fixes (might take a couple of hours before it shows up in maven central)
