### ISSUE TITLE
Cannot receive multiple messages

### ISSUE THREAD

**Issue by shuroo** [kifi/franz#53]
Hi,

I am trying to receive multiple messages from the queue in order to handle them.  I'm working with Scala Under Play-2.3.10

Yet,I don't manage to.

Previous Investigation has shown it maybe related to the maxNumberOfMessages param.

Yet, We couldn't find a way to set it via Franz and Scala.

Many Thanks,
Shiri.

**Comment by shuroo** [comment]
Hi,

This is my code:

 def receive_multi = {
    Logger.debug("in receive")
    queue.nextBatchWithLock(10, new FiniteDuration(0, SECONDS)).map(_.map(handleEmails(_)))
  }

I can only fetch the first element from the queue currently...

Thanks.

**Comment by shuroo** [comment]
@stkem , 

Please Notice. As this issue is quite urgent to us.

Thanks.

**Comment by stkem** [comment]
@shuroo I can see anything obviously wrong with the code snippet you posted. What version are you using and are you using the buffering support in the SQS client?
If you are on 0.3.10 it might help to set `buffered=false` explicitly when creating your `SQSClient`

**Comment by shuroo** [comment]
Hi,

I previously used (buffered = false), and got a different issue when I wasn't able to fetch any message from the SQS at all.

I am using play 2.3.10 with franz 0.3.10.

Attached the queue generation code.

-----


 val accessKey: String = current.configuration.getString("aws.access.key").get
    val secKey: String = current.configuration.getString("aws.secret.key").get
    val credentials = new AWSCredentials {
      def getAWSAccessKeyId() = accessKey

      def getAWSSecretKey() = secKey
    }
    val credentialProvider = new AWSCredentialsProvider {
      def getCredentials() = credentials

      def refresh() = {}
    }
    val sqs = new SimpleSQSClient(credentialProvider, com.amazonaws.regions.Regions.DEFAULT_REGION, false)

    sqs.formatted[FLMsg](QueueName("sqs-informer-queue"), true)

-----

Is there a way of manually setting the maxNumberOfMessages? 

I tried setting it from the application.conf, but it has no effect.

Many thanks.

**Comment by stkem** [comment]
Just to confirm, are you able to receive messages if you don't use batches?

**Comment by shuroo** [comment]
Hi,

Yes. I am able to receive a sungle message while using "next" method as
well.

**Comment by shuroo** [comment]
just to clarify: batch works but I only get one item each time. If my queue holds 10 msgs I need to call the batch 10 times ... something is wrong ... please advice

**Comment by stkem** [comment]
I am unable to reproduce. Could you post a complete example (i.e. producer and consumer) that reproduces this problem?

**Comment by shuroo** [comment]
Yes. 

I'm providing some of the code. If you would not be able to reproduce I may provide you the entire code via email.

The problematic method is the "receive_multi" method attached.

----------------------------------------------------------------Build.sbt-------------------------------------------------------------name := """informer"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  jdbc,
  anorm,
  cache,
  ws,
  "com.typesafe.play" %% "play-mailer" % "2.4.1",
  "com.kifi" %% "franz" % "0.3.10"
)

version := "1.0-SNAPSHOT"

------------------------------------------------------------App.config:-----------------------------------------------------------
# This is the main configuration file for the application.
# ~~~~~

# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
#
# This must be changed for production, but we recommend not changing it in this file.
#
# See http://www.playframework.com/documentation/latest/ApplicationSecret for more details.
application.secret="uY@FQg[GqP?rhUB9I76yCK]XM5CjGcAVJ;_V`g7k;tugn3R^AV;E3hZ;_[w=rT/u"

# The application languages
# ~~~~~
application.langs="en"

# Global object class
# ~~~~~
# Define the Global object class for this application.
# Default to Global in the root package.
# application.global=Global

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# application.router=my.application.Routes

# Database configuration
# ~~~~~
# You can declare as many datasources as you want.
# By convention, the default datasource is named `default`
#
# db.default.driver=org.h2.Driver
# db.default.url="jdbc:h2:mem:play"
# db.default.user=sa
# db.default.password=""

# Evolutions
# ~~~~~
# You can disable evolutions if needed
# evolutionplugin=disabled

# Logger
# ~~~~~
# You can also configure logback (http://logback.qos.ch/),
# by providing an application-logger.xml file in the conf directory.

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=DEBUG

smtp {
  host = "smtp.sendgrid.net"
  port = "587"
  ssl=false
  tls=true
  user = "firelayers-playapp"
  password = "***************"
  debug = yes
  mock = no
}

## Amazon Credentials
aws.access.key = "***********************************"
aws.secret.key = "************************************"

## Amazon SQS configuration
aws.sqs.maxNumberOfMessages=1000

------------------------------------------------------------FLMsg class:--------------------------------------------------------package models

import com.amazonaws.auth.{AWSCredentialsProvider, AWSCredentials}
import com.amazonaws.regions.Regions
import com.kifi.franz._
import play.Logger
import play.api.Play.current
import play.api.libs.json.Format
import play.api.libs.mailer.Email
import scala.concurrent.{Future, ExecutionContext}
import play.api.libs.concurrent.Execution.Implicits._
import scala.concurrent.duration._

/**
 * Created by shirirave on 9/8/15.
 */
case class FLSqsQueue() {}

object FLSqsQueue {

  val queue: SQSQueue[FLMsg] = init()

  def init(): SQSQueue[FLMsg] = {
    val accessKey: String = current.configuration.getString("aws.access.key").get
    val secKey: String = current.configuration.getString("aws.secret.key").get
    val credentials = new AWSCredentials {
      def getAWSAccessKeyId() = accessKey

      def getAWSSecretKey() = secKey
    }
    val credentialProvider = new AWSCredentialsProvider {
      def getCredentials() = credentials

      def refresh() = {}
    }
    val sqs = new SimpleSQSClient(credentialProvider, com.amazonaws.regions.Regions.DEFAULT_REGION, false)

    sqs.formatted[FLMsg](QueueName("sqs-informer-queue"), true)
  } 

  def send(param: FLMsg) = {
    queue.send(param)
  }

  def receive = {
    Logger.debug("in receive")

    queue.next.map(maybe_sqs_msg => maybe_sqs_msg match {
      case Some(msg) => handleEmails(msg)
      case None => "something else entirely"
    })

  }

  def receive_multi = {
    Logger.debug("in receive")
    queue.nextBatchWithLock(10, new FiniteDuration(0, SECONDS)).map(_.map(handleEmails(_)))
  }

  def handleEmails(sqs_msg: SQSMessage[FLMsg]): Unit = {

    sqs_msg.consume(body => {
      Logger.debug(s"XXXXXXX------Received Message:---------$sqs_msg")

      FLEmailMsg.handleReceivedEmail(body)
    })

  }


}

**Comment by shuroo** [comment]
@stkem , Did you manage to reproduce it?

If not, I can send you the code to your email address do that you could see the problem..

Thanks.

**Comment by stkem** [comment]
Hi @shuroo, your last message here was really illegible. Please pay attention to correct usage of Github Markdown. 
If you can provide a *concise* example (i.e. just the producer and consumer parts of the messages, not an entire play app; config files and routes and such are not helpful) that reproduces the problem here that would be great. I'm afraid I cannot help debugging your full application.

**Comment by shuroo** [comment]
@stkem Ok.

This is the queue ("producer") initialiser:

class FLSqsQueue{

def init(): SQSQueue[FLMsg] = {
val accessKey: String = current.configuration.getString("aws.access.key").get
val secKey: String = current.configuration.getString("aws.secret.key").get
val credentials = new AWSCredentials {
def getAWSAccessKeyId() = accessKey

  def getAWSSecretKey() = secKey
}
val credentialProvider = new AWSCredentialsProvider {
  def getCredentials() = credentials

  def refresh() = {}
}
val sqs = new SimpleSQSClient(credentialProvider, com.amazonaws.regions.Regions.DEFAULT_REGION, false)

sqs.formatted[FLMsg](QueueName("sqs-informer-queue"), true)
}
 
def send(param: FLMsg) = {
  queue.send(param)
}
}
--------------------------------------------------------------------------------------

The Consumer:

Fetching message from the queue:

def receive_multi = {
Logger.debug("in receive")
queue.nextBatchWithLock(10, new FiniteDuration(0, SECONDS)).map(.map(handleEmails()))
}

Adding a message to the queue:

def sendJson = Action.async(BodyParsers.parse.json) { request =>
Logger.debug("sending email request in process")

val nameResult: JsResult[FLMsg] = (request.body).validate[FLMsg]
nameResult.fold(
  errors => {
    Future.successful(BadRequest(Json.obj("status" ->"KO", "message" -> JsError.toFlatJson(errors))))
  },
  jsonMsg => {
    val msg: FLMsg = jsonMsg
    FLSqsQueue.send(msg)  /// this will call queue.send(msg)

    Future.successful(Ok("Email sent."))
  })

THANKS!

**Comment by stkem** [comment]
Would you mind fixing the formatting? This is incredibly hard to read (Github posts are Markdown, not plain text)
