### ISSUE TITLE
Possibility of duplicate queue reads via nextBatchRequestWithLock?

### ISSUE THREAD

**Issue by kdrakon** [kifi/franz#69]
In `SQSQueue.scala`, I can see that `nextBatchRequestWithLock` creates a `ReceiveMessageRequest` , asynchronously submits that to an SQS queue, and returns a `Future` of the eventual `SQSMessage` result. I've been trying to Google the answer to this question, but is it safe to assume that on the SQS/AWS side, the `ReceiveMessageRequest`'s will be processed in sequence of submission **and** that the eventual `ReceiveMessageResult`'s will be distinct across the async `Future`'s created?

My concern comes from the fact that I have a scenario where I will be firing off n requests to `nextWithLock` in very very close sequence (ns to ms). I'm wondering if I should write code to ensure distinctness of received messages across these requests.

**Comment by stkem** [comment]
I'm afraid AWS does guarantee any processing order of request that come in in very close succession due to the distributed nature of SQS. I.e. in your scenario you are likely going to get some duplicate messages. 
Why are you making these quick succession requests? If you just want to process a bunch of messages concurrently it would be safer (and likely faster) to use `nextBatchWithLock` and parallelize after you get the response.

**Comment by kdrakon** [comment]
For clarification, I'm using Akka for concurrent requests to read from SQS where my queues are populated at high frequencies by another system. Originally, I was using `nextBatchWithLock` from a single actor and then distributing the messages to _worker_ actors as you suggested. Because this didn't initially provide the best solution for back pressure (i.e. I could potentially OOM kill the workers mailboxes under high SQS message throughput), I reversed the relationship so that the worker actors requested work from the single actor (i.e. with `nextWithLock`). In this pattern, the workers would quickly process their work message, ask for more, and never be overburdened. It was the "ask for more" part that was causing the quick succession of requests via franz.

Hypothetically, if I had a "loop" make sequential `nextBatchWithLock` requests in batches of 10, would I less likely retrieve duplicates from SQS? Ideally, I wouldn't make subsequent requests until the previous one was `Future` completed. Potentially, I could offload these messages to a buffer queue that my worker actors would read from.

Thanks for the help and very useful info about SQS.

**Comment by stkem** [comment]
Yup, if you make batch requests sequentially (i.e. only fire the next one after the previous has finished) you'd mostly avoid the duplicate problem. SQS still doesn't give any hard guarantees, but in my experience this pattern is safe.
